@echo off
echo Cleaning up redundant documentation files...

del "CODE_QUALITY_AUDIT_REPORT.md" 2>nul
del "PERSONA_QA_VALIDATION_REPORT.md" 2>nul
del "CONTEXTUAL_TIMELINE_REDESIGN.md" 2>nul
del "CFA_LIFECYCLE_ANALYSIS_REPORT.md" 2>nul
del "GOAL_TRACKING_ASSESSMENT_REPORT.md" 2>nul
del "PREDICTIVE_ANALYTICS_IMPLEMENTATION_REPORT.md" 2>nul
del "COMPREHENSIVE_INTEGRATION_VALIDATION_REPORT.md" 2>nul
del "COMPREHENSIVE_USER_JOURNEY_VALIDATION_REPORT.md" 2>nul
del "BUDGET_INTEGRATION_PERSONA_VALIDATION_REPORT.md" 2>nul
del "MIGRATION_PLAN.md" 2>nul
del "CLEAN_ARCHITECTURE_TEST_SUMMARY.md" 2>nul
del "BUDGET_INTEGRATION_EPIC.md" 2>nul
del ".delete_files.txt" 2>nul

echo Cleanup complete.