services:
  db:
    image: postgres:15
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    # BUILD FROM REPO ROOT so compute/ is included
    build:
      context: .
      dockerfile: api/Dockerfile
    env_file:
      - ./.env
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: /app/wait-for-it.sh db:5432 -- /usr/local/bin/uvicorn api.app.main:app --host 0.0.0.0 --port 8000 --log-level debug

  frontend:
    build: ./frontend
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
    volumes:
      - ./frontend:/app

volumes:
  db_data:
