services:
  db:
    image: postgres:15
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: ./api
    env_file:
      - ./.env
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    env_file:
      - ./.env   # only if you’ve added VITE_API_URL there
    ports:
      - "3000:3000"

volumes:
  db_data:
