# Development optimizations for faster builds
version: '3.8'

services:
  frontend:
    build:
      target: development
    volumes:
      # Mount source code for hot reloading (faster development)
      - ./frontend/src:/app/src:cached
      - ./frontend/public:/app/public:cached
      # Named volume for node_modules (faster than host mount)
      - frontend_node_modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_BASE_URL=http://localhost:8000

  api:
    volumes:
      # Mount source code for hot reloading
      - ./api:/app/api:cached
      - ./compute:/app/compute:cached
    environment:
      - PYTHON_ENV=development

volumes:
  frontend_node_modules: