"""
Income Domain Entity - Clean Architecture Implementation
CFA-compliant income management with asset relationship modeling
"""
from dataclasses import dataclass
from typing import Optional
from datetime import datetime, timezone
from decimal import Decimal
from enum import Enum

from .money import Money


class IncomeType(Enum):
    """CFA-standard income classifications for comprehensive tracking"""
    # Employment Income (W-2 equivalent)
    SALARY = "salary"
    WAGES = "wages" 
    BONUS = "bonus"
    COMMISSION = "commission"
    
    # Business Income (1099 equivalent)
    BUSINESS_INCOME = "business_income"
    SELF_EMPLOYMENT = "self_employment"
    CONSULTING = "consulting"
    FREELANCE = "freelance"
    
    # Investment Income
    DIVIDENDS = "dividends"
    INTEREST = "interest"
    CAPITAL_GAINS = "capital_gains"
    RENTAL_INCOME = "rental_income"
    
    # Other Income
    PENSION = "pension"
    SOCIAL_SECURITY = "social_security"
    GOVERNMENT_BENEFITS = "government_benefits"
    GIFTS = "gifts"
    OTHER = "other"


class IncomeFrequency(Enum):
    """Income payment frequency"""
    MONTHLY = "monthly"
    QUARTERLY = "quarterly"
    ANNUALLY = "annually"
    WEEKLY = "weekly"
    BIWEEKLY = "biweekly"
    IRREGULAR = "irregular"


class TemporalPattern(Enum):
    """Temporal characteristics of income streams"""
    PERMANENT = "permanent"          # Ongoing indefinitely (salary, pension)
    TEMPORARY = "temporary"          # Fixed duration (contract, seasonal)
    PROJECT_BASED = "project_based"  # Specific project completion
    SEASONAL = "seasonal"            # Recurring seasonal pattern


@dataclass
class Income:
    """
    Income domain entity for comprehensive income tracking and analysis.
    
    Following CFA standards for:
    - Income classification and categorization
    - Asset relationship modeling (rental, business, investment income)
    - Temporal analysis for cash flow projections
    - Tax treatment classification for optimization
    """
    # Core Identity
    id: int
    user_id: int
    
    # Income Details
    description: str
    amount: Money
    income_type: IncomeType
    frequency: IncomeFrequency
    
    # Temporal Characteristics
    is_recurring: bool = True
    start_date: Optional[datetime] = None
    end_date: Optional[datetime] = None
    temporal_pattern: TemporalPattern = TemporalPattern.PERMANENT
    
    # Asset Relationship (KISS User Selection)
    linked_asset_id: Optional[int] = None
    asset_relationship_type: Optional[str] = None  # "rental", "business_operations", "investment_return"
    
    # Financial Planning Integration
    is_taxable: bool = True
    tax_category: Optional[str] = None  # "employment", "business", "investment", "other"
    growth_rate: Optional[Decimal] = None  # Annual income growth assumption
    
    # Metadata
    is_active: bool = True
    notes: Optional[str] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    
    def __post_init__(self):
        """Initialize calculated fields and validate data"""
        if self.created_at is None:
            self.created_at = datetime.now(timezone.utc)
        if self.updated_at is None:
            self.updated_at = datetime.now(timezone.utc)
    
    def calculate_monthly_amount(self) -> Money:
        """
        Convert income to monthly equivalent for budgeting.
        
        Returns:
            Money: Monthly equivalent amount
        """
        if self.frequency == IncomeFrequency.MONTHLY:
            return self.amount
        elif self.frequency == IncomeFrequency.QUARTERLY:
            return Money(self.amount.amount / 3, self.amount.currency)
        elif self.frequency == IncomeFrequency.ANNUALLY:
            return Money(self.amount.amount / 12, self.amount.currency)
        elif self.frequency == IncomeFrequency.WEEKLY:
            return Money(self.amount.amount * Decimal('4.33'), self.amount.currency)
        elif self.frequency == IncomeFrequency.BIWEEKLY:
            return Money(self.amount.amount * Decimal('2.17'), self.amount.currency)
        else:  # IRREGULAR
            return Money.zero(self.amount.currency)
    
    def calculate_annual_amount(self) -> Money:
        """
        Calculate annual income amount for financial planning.
        
        Returns:
            Money: Annual income amount
        """
        monthly = self.calculate_monthly_amount()
        return Money(monthly.amount * 12, monthly.currency)
    
    def is_asset_linked_income(self) -> bool:
        """
        Check if income is generated by an asset.
        
        Returns:
            bool: True if income is linked to an asset
        """
        return (
            self.linked_asset_id is not None or
            self.income_type in {
                IncomeType.RENTAL_INCOME,
                IncomeType.DIVIDENDS,
                IncomeType.INTEREST,
                IncomeType.BUSINESS_INCOME
            }
        )
    
    def get_income_stability_score(self) -> int:
        """
        Calculate income stability score (1-10 scale) for financial planning.
        
        Returns:
            int: Stability score from 1 (unstable) to 10 (very stable)
        """
        base_score = 5  # Default moderate stability
        
        # Adjust based on income type
        stability_scores = {
            IncomeType.SALARY: 9,
            IncomeType.PENSION: 10,
            IncomeType.GOVERNMENT_BENEFITS: 8,
            IncomeType.RENTAL_INCOME: 7,
            IncomeType.DIVIDENDS: 6,
            IncomeType.BUSINESS_INCOME: 4,
            IncomeType.CONSULTING: 3,
            IncomeType.FREELANCE: 2,
            IncomeType.COMMISSION: 3,
            IncomeType.BONUS: 2
        }
        
        type_score = stability_scores.get(self.income_type, base_score)
        
        # Adjust based on temporal pattern
        if self.temporal_pattern == TemporalPattern.PERMANENT:
            type_score += 1
        elif self.temporal_pattern == TemporalPattern.TEMPORARY:
            type_score -= 2
        elif self.temporal_pattern == TemporalPattern.PROJECT_BASED:
            type_score -= 3
        
        # Clamp to 1-10 range
        return max(1, min(10, type_score))
    
    def calculate_present_value(self, discount_rate: Decimal = Decimal('0.125'), years: int = 30) -> Money:
        """
        Calculate present value of income stream for human capital analysis.
        
        Args:
            discount_rate: Discount rate for PV calculation (default 12.5% for Kenya)
            years: Number of years to project (default 30)
            
        Returns:
            Money: Present value of future income stream
        """
        if not self.is_recurring:
            return self.amount  # One-time income
        
        annual_income = self.calculate_annual_amount()
        growth_rate = self.growth_rate or Decimal('0.03')  # Default 3% growth
        
        pv_total = Decimal('0.00')
        for year in range(1, years + 1):
            # Apply growth to income
            future_income = annual_income.amount * ((1 + growth_rate) ** year)
            
            # Discount to present value
            pv_factor = (1 + discount_rate) ** year
            pv_year = future_income / pv_factor
            
            pv_total += pv_year
            
            # Handle temporary income streams
            if (self.end_date and 
                self.end_date <= datetime.now(timezone.utc).replace(year=datetime.now().year + year)):
                break
        
        return Money(pv_total, annual_income.currency)
    
    def get_tax_treatment_category(self) -> str:
        """
        Determine tax treatment category for Kenya tax system.
        
        Returns:
            str: Tax category for proper tax planning
        """
        employment_types = {
            IncomeType.SALARY, IncomeType.WAGES, 
            IncomeType.BONUS, IncomeType.COMMISSION
        }
        
        business_types = {
            IncomeType.BUSINESS_INCOME, IncomeType.SELF_EMPLOYMENT,
            IncomeType.CONSULTING, IncomeType.FREELANCE
        }
        
        investment_types = {
            IncomeType.DIVIDENDS, IncomeType.INTEREST,
            IncomeType.CAPITAL_GAINS, IncomeType.RENTAL_INCOME
        }
        
        if self.income_type in employment_types:
            return "employment"
        elif self.income_type in business_types:
            return "business"
        elif self.income_type in investment_types:
            return "investment"
        else:
            return "other"
    
    def to_dict(self) -> dict:
        """Convert income to dictionary for API serialization"""
        return {
            "id": self.id,
            "description": self.description,
            "amount": self.amount.to_dict(),
            "income_type": self.income_type.value,
            "frequency": self.frequency.value,
            "monthly_equivalent": self.calculate_monthly_amount().to_dict(),
            "annual_equivalent": self.calculate_annual_amount().to_dict(),
            "is_recurring": self.is_recurring,
            "start_date": self.start_date.isoformat() if self.start_date else None,
            "end_date": self.end_date.isoformat() if self.end_date else None,
            "temporal_pattern": self.temporal_pattern.value,
            "linked_asset_id": self.linked_asset_id,
            "asset_relationship_type": self.asset_relationship_type,
            "is_taxable": self.is_taxable,
            "tax_category": self.get_tax_treatment_category(),
            "growth_rate": float(self.growth_rate) if self.growth_rate else None,
            "stability_score": self.get_income_stability_score(),
            "is_asset_linked": self.is_asset_linked_income(),
            "notes": self.notes,
            "is_active": self.is_active,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "updated_at": self.updated_at.isoformat() if self.updated_at else None
        }