name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:15
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: pass
          POSTGRES_DB: finance_app
        ports: ["5432:5432"]
        options: >-
          --health-cmd "pg_isready -U user"
          --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install API dependencies
        run: |
          cd api
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        - name: Run API tests with coverage
          run: |
            pytest --cov-report=xml
      - name: Enforce API coverage ≥ 90 %
        run: |
          coverage report --fail-under=90

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install all JS dependencies
        run: npm ci

      - name: Run frontend tests
        working-directory: frontend
        run: npm test -- --coverage --watchAll=false

      - name: Build Docker images
        run: |
          docker build -t finance-api:pr-${{ github.sha }} -f api/Dockerfile api
          docker build -t finance-frontend:pr-${{ github.sha }} -f frontend/Dockerfile frontend
