name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:15
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: pass
          POSTGRES_DB: finance_app
        ports: ["5432:5432"]
        options: >-
          --health-cmd "pg_isready -U user"
          --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install API dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Run API tests with coverage
        run: |
          pytest --cov-report=xml
      - name: Enforce API coverage ≥ 90 %
        run: |
          coverage report --fail-under=90

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Frontend dependencies
        run: |
          cd frontend
          npm install
      - name: Run Frontend tests with coverage
        run: |
          cd frontend
          npm test -- --coverage

      - name: Run Playwright e2e tests
        run: |
          cd frontend
          npx playwright install --with-deps
          npx playwright test

      - name: Run contract tests
        run: |
          pytest frontend/tests/contract

      - name: Build Docker images
        run: |
          docker build -t finance-api:pr-${{ github.sha }} -f api/Dockerfile api
          docker build -t finance-frontend:pr-${{ github.sha }} -f frontend/Dockerfile frontend
