jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:15
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: pass
          POSTGRES_DB: finance_app
        options: >-
          --health-cmd "pg_isready -U user"
          --health-interval 10s --health-retries 5

    steps:
      - uses: actions/checkout@v3

      # Python tests
      - name: Setup Python
        uses: actions/setup-python@v4
        with: python-version: '3.11'
      - name: Install API deps
        run: |
          pip install --upgrade pip setuptools wheel
          pip install -r api/requirements.txt
      - name: Run API tests
        run: |
          pytest --cov=app --cov=compute --cov-report=xml
      - name: Enforce API coverage
        run: |
          coverage report --fail-under=90

      # Node.js tests
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with: node-version: '18'
      - name: Install Frontend deps
        run: |
          cd frontend
          npm ci
      - name: Run Frontend tests
        run: |
          cd frontend
          npm test -- --coverage

      # Docker build
      - name: Build API image
        run: docker build -t finance-api:ci -f api/Dockerfile api
      - name: Build Frontend image
        run: docker build -t finance-frontend:ci -f frontend/Dockerfile frontend
